const styles = {

  // ── LOGIN ──────────────────────────────────────────────────────────────────
  loginBg: {
    minHeight: "100vh",
    background: "#060d16",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "'Courier New', monospace",
    position: "relative",
    overflow: "hidden",
  },
  loginGlow: {
    position: "absolute",
    width: 600,
    height: 600,
    borderRadius: "50%",
    background: "radial-gradient(circle, #1a3a5c33 0%, transparent 70%)",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    pointerEvents: "none",
  },
  loginCard: {
    background: "#0a1520",
    border: "1px solid #1e3a5f",
    borderRadius: 12,
    padding: 40,
    width: 520,
    position: "relative",
    zIndex: 1,
  },
  loginHeader:   { textAlign: "center", marginBottom: 28 },
  loginBadge:    { fontSize: 40, color: "#6c91c2", display: "block", marginBottom: 8 },
  loginTitle:    { color: "#e8edf5", fontSize: 24, fontWeight: 900, letterSpacing: 8, margin: "0 0 4px" },
  loginSubtitle: { color: "#8892a4", fontSize: 12, letterSpacing: 2, margin: 0 },
  loginDivider:  { height: 1, background: "linear-gradient(90deg, transparent, #1e3a5f, transparent)", margin: "16px 0 10px" },
  loginClearance:{ color: "#e6394666", fontSize: 11, letterSpacing: 3 },

  loginQuickAccess: { marginBottom: 24 },
  loginQuickLabel:  { color: "#8892a4", fontSize: 10, letterSpacing: 3, marginBottom: 10 },
  loginRoleGrid:    { display: "flex", gap: 8, flexWrap: "wrap" },
  loginRoleBtn: {
    flex: "1 1 140px",
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "#0d1b2a",
    border: "1px solid #1e3a5f",
    borderRadius: 8,
    padding: "8px 12px",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  loginRoleBtnActive: { background: "#1a3a5c", border: "1px solid #4a7fa8" },
  loginRoleDot:       { width: 8, height: 8, borderRadius: "50%", flexShrink: 0 },
  loginRoleName:      { color: "#c8d4e0", fontSize: 12, fontWeight: 700 },
  loginRoleType:      { color: "#8892a4", fontSize: 10 },

  loginFields: { display: "flex", flexDirection: "column", gap: 12 },
  loginLabel: {
    color: "#8892a4",
    fontSize: 10,
    letterSpacing: 3,
    display: "block",
    marginBottom: 4,
  },
  loginInput: {
    width: "100%",
    background: "#060d16",
    border: "1px solid #1e3a5f",
    borderRadius: 6,
    padding: "10px 14px",
    color: "#e8edf5",
    fontSize: 14,
    fontFamily: "'Courier New', monospace",
    boxSizing: "border-box",
    outline: "none",
  },
  loginError: { color: "#e63946", fontSize: 12, margin: 0 },
  loginBtn: {
    background: "linear-gradient(135deg, #1a3a5c, #2a5a8c)",
    border: "1px solid #4a7fa8",
    borderRadius: 6,
    padding: "12px 24px",
    color: "#e8edf5",
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: 3,
    cursor: "pointer",
    marginTop: 4,
  },

  // ── APP SHELL ──────────────────────────────────────────────────────────────
  appShell: {
    minHeight: "100vh",
    background: "#060d16",
    color: "#c8d4e0",
    fontFamily: "'Courier New', monospace",
  },

  // ── NAV ────────────────────────────────────────────────────────────────────
  nav: {
    display: "flex",
    alignItems: "center",
    gap: 24,
    background: "#0a1520",
    borderBottom: "1px solid #1e3a5f",
    padding: "0 24px",
    height: 56,
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  navLogo:      { display: "flex", alignItems: "center", gap: 10, marginRight: 16 },
  navLogoIcon:  { color: "#6c91c2", fontSize: 22 },
  navLogoBlock: { display: "flex", flexDirection: "column", lineHeight: 1 },
  navLogoText:  { color: "#e8edf5", fontWeight: 900, letterSpacing: 4, fontSize: 14 },
  navLogoSub:   { color: "#4a7fa8", fontSize: 9, letterSpacing: 3, marginTop: 2 },
  navItems:     { display: "flex", gap: 4, flex: 1 },
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "transparent",
    border: "none",
    color: "#8892a4",
    padding: "6px 14px",
    borderRadius: 6,
    cursor: "pointer",
    fontSize: 12,
    letterSpacing: 1,
    fontFamily: "'Courier New', monospace",
    transition: "all 0.2s",
  },
  navItemActive: { background: "#1a3a5c", color: "#6c91c2", border: "none" },
  navItemIcon:   { fontSize: 14 },
  navUser:       { display: "flex", alignItems: "center", gap: 12, marginLeft: "auto" },
  navRolePill:   { display: "flex", alignItems: "center", gap: 6, padding: "4px 10px", borderRadius: 20 },
  navRoleDot:    { width: 6, height: 6, borderRadius: "50%" },
  navRoleText:   { fontSize: 10, fontWeight: 700, letterSpacing: 1 },
  navUserName:   { color: "#c8d4e0", fontSize: 12 },
  navLogout: {
    background: "transparent",
    border: "1px solid #1e3a5f",
    color: "#8892a4",
    padding: "4px 12px",
    borderRadius: 4,
    cursor: "pointer",
    fontSize: 11,
    letterSpacing: 1,
    fontFamily: "'Courier New', monospace",
  },

  // ── PAGE LAYOUT ────────────────────────────────────────────────────────────
  page:       { padding: "28px 32px", maxWidth: 1400, margin: "0 auto" },
  pageHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 28,
    flexWrap: "wrap",
    gap: 16,
  },
  pageTitle:    { color: "#e8edf5", fontSize: 20, fontWeight: 900, letterSpacing: 4, margin: "0 0 4px" },
  pageSubtitle: { color: "#8892a4", fontSize: 12, letterSpacing: 1, margin: 0 },

  // ── STAT CARDS ─────────────────────────────────────────────────────────────
  statGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
    gap: 16,
    marginBottom: 28,
  },
  statCard: {
    background: "#0a1520",
    border: "1px solid #1e3a5f",
    borderRadius: 10,
    padding: "20px 20px 16px",
    position: "relative",
    overflow: "hidden",
    transition: "all 0.2s",
  },
  statCardHover:  { background: "#0d1f30", border: "1px solid #2a5a8c", transform: "translateY(-2px)" },
  statCardAccent: { position: "absolute", top: 0, left: 0, right: 0, height: 3, borderRadius: "10px 10px 0 0" },
  statCardLabel:  { color: "#8892a4", fontSize: 10, letterSpacing: 2, marginBottom: 8 },
  statCardValue:  { fontSize: 28, fontWeight: 900, lineHeight: 1 },
  statCardSub:    { color: "#8892a4", fontSize: 10, marginTop: 6 },
  statCardClick:  { fontSize: 10, marginTop: 8, letterSpacing: 1, opacity: 0.7 },

  // ── FILTERS ────────────────────────────────────────────────────────────────
  filterRow: { display: "flex", gap: 12, marginBottom: 20, flexWrap: "wrap" },
  select: {
    background: "#0a1520",
    border: "1px solid #1e3a5f",
    borderRadius: 6,
    padding: "8px 12px",
    color: "#c8d4e0",
    fontSize: 12,
    fontFamily: "'Courier New', monospace",
    outline: "none",
    cursor: "pointer",
  },

  // ── TABLE ──────────────────────────────────────────────────────────────────
  tableWrapper: { background: "#0a1520", border: "1px solid #1e3a5f", borderRadius: 10, overflow: "hidden" },
  tableHeader:  {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 20px",
    borderBottom: "1px solid #1e3a5f",
  },
  tableTitle:  { color: "#e8edf5", fontSize: 12, fontWeight: 700, letterSpacing: 3 },
  tableBadge:  { background: "#1a3a5c", color: "#6c91c2", padding: "2px 10px", borderRadius: 10, fontSize: 11 },
  tableScroll: { overflowX: "auto" },
  table:       { width: "100%", borderCollapse: "collapse" },
  th: {
    padding: "10px 16px",
    textAlign: "left",
    color: "#8892a4",
    fontSize: 10,
    letterSpacing: 2,
    borderBottom: "1px solid #1e3a5f",
    whiteSpace: "nowrap",
    background: "#080f1a",
  },
  tr: { borderBottom: "1px solid #1e3a5f11", transition: "background 0.1s" },
  td: { padding: "10px 16px", fontSize: 12, color: "#c8d4e0", whiteSpace: "nowrap" },

  // ── BADGES & PILLS ─────────────────────────────────────────────────────────
  basePill: {
    background: "#1a3a5c44",
    color: "#6c91c2",
    border: "1px solid #1e3a5f",
    padding: "2px 8px",
    borderRadius: 4,
    fontSize: 11,
  },
  netBadge: {
    color: "#f4a261",
    cursor: "pointer",
    background: "#f4a26122",
    border: "1px solid #f4a26144",
    padding: "2px 8px",
    borderRadius: 4,
    fontSize: 11,
  },
  statusPill:     { padding: "3px 10px", borderRadius: 10, fontSize: 11, fontWeight: 700 },
  statusComplete: { background: "#2a9d8f22", color: "#2a9d8f", border: "1px solid #2a9d8f44" },
  statusTransit:  { background: "#f4a26122", color: "#f4a261", border: "1px solid #f4a26144" },
  typeAssigned:   { background: "#e9c46a22", color: "#e9c46a", border: "1px solid #e9c46a44" },
  typeExpended:   { background: "#e6394622", color: "#e63946", border: "1px solid #e6394644" },

  // ── BUTTONS ────────────────────────────────────────────────────────────────
  primaryBtn: {
    background: "linear-gradient(135deg, #1a3a5c, #2a5a8c)",
    border: "1px solid #4a7fa8",
    borderRadius: 6,
    padding: "10px 20px",
    color: "#e8edf5",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 2,
    cursor: "pointer",
    fontFamily: "'Courier New', monospace",
    whiteSpace: "nowrap",
  },
  smallBtn: {
    background: "#0d1b2a",
    border: "1px solid #2a9d8f44",
    borderRadius: 4,
    padding: "4px 10px",
    color: "#2a9d8f",
    fontSize: 11,
    cursor: "pointer",
    fontFamily: "'Courier New', monospace",
  },

  // ── FORM ───────────────────────────────────────────────────────────────────
  formCard:  { background: "#0d1b2a", border: "1px solid #1e3a5f", borderRadius: 10, padding: 24, marginBottom: 24 },
  formTitle: { color: "#e8edf5", fontSize: 13, fontWeight: 700, letterSpacing: 3, marginTop: 0, marginBottom: 20 },
  formGrid:  { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 16, marginBottom: 20 },
  formField: { display: "flex", flexDirection: "column", gap: 6 },
  formLabel: { color: "#8892a4", fontSize: 10, letterSpacing: 2 },
  formInput: {
    background: "#060d16",
    border: "1px solid #1e3a5f",
    borderRadius: 6,
    padding: "8px 12px",
    color: "#e8edf5",
    fontSize: 13,
    fontFamily: "'Courier New', monospace",
    outline: "none",
    boxSizing: "border-box",
    width: "100%",
  },

  // ── BANNERS ────────────────────────────────────────────────────────────────
  successBanner: {
    background: "#2a9d8f22",
    border: "1px solid #2a9d8f44",
    borderRadius: 6,
    padding: "10px 16px",
    color: "#2a9d8f",
    fontSize: 12,
    marginBottom: 20,
    letterSpacing: 1,
  },
  errorBanner: {
    background: "#e6394622",
    border: "1px solid #e6394444",
    borderRadius: 6,
    padding: "10px 16px",
    color: "#e63946",
    fontSize: 12,
    marginBottom: 20,
    letterSpacing: 1,
  },

  // ── MODAL ──────────────────────────────────────────────────────────────────
  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "#00000088",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 200,
  },
  modal: {
    background: "#0a1520",
    border: "1px solid #2a5a8c",
    borderRadius: 12,
    padding: 32,
    minWidth: 480,
    maxWidth: 600,
    width: "90%",
  },
  modalHeader:    { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 6 },
  modalTitle:     { color: "#e8edf5", fontSize: 16, fontWeight: 900, letterSpacing: 3, margin: 0 },
  modalClose:     { background: "transparent", border: "none", color: "#8892a4", fontSize: 18, cursor: "pointer" },
  modalSub:       { color: "#8892a4", fontSize: 12, marginBottom: 24, letterSpacing: 1 },
  modalGrid:      { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 16, marginBottom: 24 },
  modalStatCard:  { background: "#0d1b2a", border: "1px solid", borderRadius: 8, padding: "16px 12px", textAlign: "center" },
  modalStatLabel: { color: "#8892a4", fontSize: 11, letterSpacing: 1, marginTop: 6, marginBottom: 4 },
  modalStatValue: { fontSize: 24, fontWeight: 900 },
  modalNetRow:    {
    background: "#080f1a",
    border: "1px solid #1e3a5f",
    borderRadius: 8,
    padding: 16,
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  modalNetLabel:   { color: "#8892a4", fontSize: 11, letterSpacing: 2 },
  modalNetFormula: { color: "#c8d4e0", fontSize: 12, flex: 1 },
  modalNetResult:  { color: "#f4a261", fontSize: 20, fontWeight: 900 },

  // ── ACCESS DENIED ──────────────────────────────────────────────────────────
  accessDenied: { textAlign: "center", padding: "80px 20px" },
  accessIcon:   { fontSize: 48, color: "#e63946", marginBottom: 16 },
  accessTitle:  { color: "#e8edf5", fontSize: 18, fontWeight: 900, letterSpacing: 4, marginBottom: 8 },
  accessText:   { color: "#8892a4", fontSize: 13, maxWidth: 400, margin: "0 auto" },
};

export default styles;
